name: QA

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          npm install
      - name: Run QA
        run: |
          npm run lint
          npm run test
