name: Release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          yarn install
      - name: Release
        env:
          DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}
        run: npx semantic-release
